=== WaldaV/exersize3/Firearms.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Firearms">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Firearm" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Model" type="xs:string"/>
                            <xs:element name="Handy">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="one-handed"/>
                                        <xs:enumeration value="two-handed"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Origin" type="xs:string"/>
                            <xs:element name="TTC">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Range">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="close"/>
                                                    <xs:enumeration value="average"/>
                                                    <xs:enumeration value="distant"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="EffectiveRange" type="xs:positiveInteger" minOccurs="0">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="5000"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Clip" type="xs:boolean"/>
                                        <xs:element name="Optics" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Material" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== WaldaV/exersize3/Firearms.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Firearms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Firearms.xsd">
    <Firearm id="1">
        <Model>AK-47</Model>
        <Handy>two-handed</Handy>
        <Origin>Russia</Origin>
        <TTC>
            <Range>distant</Range>
            <EffectiveRange>1000</EffectiveRange>
            <Clip>true</Clip>
            <Optics>false</Optics>
        </TTC>
        <Material>Metal</Material>
    </Firearm>
    <Firearm id="2">
        <Model>Mauser 1934</Model>
        <Handy>one-handed</Handy>
        <Origin>German</Origin>
        <TTC>
            <Range>close</Range>
            <EffectiveRange>40</EffectiveRange>
            <Clip>true</Clip>
            <Optics>false</Optics>
        </TTC>
        <Material>Metal</Material>
    </Firearm>
</Firearms>
